### PR TITLE
(RE-13660) Add new 'vanagon' command and cli parser

### PR DESCRIPTION
**Pull request by e-gris**
Rather than vanagon use standalone 'build', 'sign', 'ship', etc. statements, I've added a new 'vanagon' command so that
'vanagon build', 'vanagon sign', 'vanagon ship', etc.  replace the above.

Please add all notable changes to the "Unreleased" section of the CHANGELOG.

### CODE REVIEW

**Review by underscorgan — COMMENTED** [review]
In general this looks really good! Main question is whether or not there's some clean-ish way to move the commands copied from `bin/[build|sign|ship]` somewhere where they could be called from the CLI and the existing commands just to reduce duplication and risk of code drift

**Comment by e-gris** [comment]
That is totally doable. My initial pass was intended to be generally additive (modulo the deprecation warnings).

For example we can make bin/build be. 

```bash
#!/bin/bash

echo "Deprecation warning"
exec vanagon build "$@"
```
This would keep backwards compatibility.

Further, I ignored some of the other vanagon commands (inspect, render, etc.) only for initial expedience. The complete version would either incorporate them into the new cli or remove them. Not sure which, if any, were still valuable to keep.

The new CLI structure allows us to add/drop/change subcommands fairly easily.

**Comment by e-gris** [comment]
The other immediately desirable/helpful thing would be to delegate the '#run' method to the subcommand objects. I just didn't get that far on Friday.

**Comment by e-gris** [comment]
@underscorgan I think I'm in a good spot. Probably could use some more testing, maybe see if Night's Watch has any opinion?

**Review by underscorgan — APPROVED** [review]
I like this!

**Comment by underscorgan** [comment]
Hiya @mihaibuzgau ! Does your team want to take a look at these potential vanagon changes?

**Pull request merged**
