### PR TITLE
(VANAGON-47) Env. var. fixups

### PR DESCRIPTION
**Pull request by mckern**
Thanks to an ungreedy (generous?) regular expression, not every value in an environment variable was being coerced. The generous regex has been updated, but while I was in there I flushed out a couple of typos and a few places where we'd hardcoded variables for the underlying shell instead of Make.

### CODE REVIEW

**Comment by mckern** [comment]
Confirmed that this builds P-A for Windows. Can do a broader test matrix to validate.

**Comment by melissa** [comment]
Have you tried building other project, like pe-client-tools with this branch?

**Comment by mckern** [comment]
I have successfully built P-A from master using this branch for the following platforms:

aix-6.1-ppc
aix-7.1-ppc
debian-7-amd64
debian-8-i386
el-5-x86_64
el-7-x86_64
osx-10.10-x86_64
solaris-10-i386
solaris-11-sparc
windows-2012r2-x86
windows-2012r2-x64

**Comment by underscorgan** [comment]
Would like to make sure it doesn't go 💥  for at least one other project (maybe the rust build AJ was trying yesterday?) but otherwise 👍

**Comment by mckern** [comment]
```
undefined local variable or method `project' for #<Vanagon::Project:0x00000002a0bca0>
/var/lib/jenkins/workspace/vanagon_generic_job/PLATFORM/windows-2012r2-x86/label/vanagon/gems/ruby/2.1.0/bundler/gems/vanagon-c1d243d11ad0/lib/vanagon/project.rb:124:in `method_missing'
(erb):10:in `generate_packaging_artifacts'
```

I don't know what's going on there but  @ajroetker found this

**Comment by mckern** [comment]
@melissa @underscorgan The rust component from pl-build-tools-vanagon has been built successfully for:

debian-7-amd64
debian-7-i386
debian-8-amd64
debian-8-i386
el-6-i386
el-6-x86_64
el-7-x86_64
sles-10-i386
sles-10-x86_64
sles-11-i386
sles-11-x86_64
sles-12-x86_64
ubuntu-10.04-amd64
ubuntu-10.04-i386
ubuntu-12.04-amd64
ubuntu-12.04-i386
ubuntu-14.04-amd64
ubuntu-14.04-i386
ubuntu-15.10-amd64
ubuntu-15.10-i386
ubuntu-16.04-amd64
ubuntu-16.04-i386
windows-2012r2-x86
windows-2012r2-x64

**Comment by underscorgan** [comment]
I think there's a particularly confusing typo in the commit message for c1d243d11ad09f67e4cfbe624d4e2fddc97193d9, I think it should be `we'll now` not `we'll not`?

**Comment by underscorgan** [comment]
otherwise, looks good! 👍

**Comment by mckern** [comment]
commit typo fixed

**Pull request merged**
