### PR TITLE
(maint) Don't follow symlinks while making file lists

### PR DESCRIPTION
**Pull request by underscorgan**
If we're linking a directory we only want to add the link, not all of
the files inside the linked directory.

### CODE REVIEW

**Comment by mckern** [comment]
What platforms has this been tested against?

**Comment by underscorgan** [comment]
Building agent with 0.9.2 + 6f6da5d556661f692bb8b5744bc18cfc0c5f5168 + this at http://jenkins-release.delivery.puppetlabs.net/job/vanagon_generic_job/709/

Currently building the same sha of puppet-agent for el6 to verify there are no differences. This has been used to build pe-activemq which needed directory linking also.

**Comment by mckern** [comment]
Can you test this on macOS and Windows? Don't care about the arch or anything -- just want to make sure we check some of our outlier platforms.

**Comment by underscorgan** [comment]
@mckern just that they install + look ok? built fine with those platforms but haven't tested installing on weirder platforms yet.

**Comment by underscorgan** [comment]
Verified that on el-6 p-a built with this vs Gemfile default had no differences (using `rpm -qplv`)

**Comment by underscorgan** [comment]
Installed on osx, was able to get versions, run facter, run puppet apply. Testing on a windows now.

**Comment by underscorgan** [comment]
Installed on windows and ran the same tests I ran on osx (versions for all the components, ran facter, puppet apply).

**Comment by shrug** [comment]
Are there any cases where we link something into the build from outside... where the package might not own the link source?

**Comment by underscorgan** [comment]
If we're linking something from outside where we don't own the source, should we own the subfiles? Would that lead to deleting something we don't own?

So like, if in some weird hypothetical packaging we need /etc/httpd linked locally and have
```
ln -s /etc/httpd /opt/myapp/httpd
```
With this the package would end up owning `/opt/myapp/httpd` but none of the other files under `/etc/httpd` and  that feels right? Though I may be thinking about this incorrectly.

**Comment by underscorgan** [comment]
investigating some weird local behaviour

**Comment by underscorgan** [comment]
rpmbuild 4.11 is stricter about file types (namely it fails if something says it's a dir but it isn't). 	f1a98ef updates our file-list-for-rpm munging to not say that links are dirs.

**Comment by shrug** [comment]
👍  pending travis

**Comment by melissa** [comment]
Can you test building razor with this?

**Comment by underscorgan** [comment]
@melissa http://jenkins-release.delivery.puppetlabs.net/job/vanagon_generic_job/ it built!

`rpm -qplv` reports no differences on el7, so should be good!

**Comment by melissa** [comment]
I would merge it, but I can't :( the button is greyed out

**Comment by underscorgan** [comment]
@melissa lemme try some force-pushing to see if i can make travis kickoff

**Pull request merged**
