### PR TITLE
(VANAGON-144) Load metadata from upstream projects

### PR DESCRIPTION
**Pull request by underscorgan**
Add ability to load upstream metadata when inheriting settings from other projects.

Please add all notable changes to the "Unreleased" section of the CHANGELOG.

### CODE REVIEW

**Comment by underscorgan** [comment]
build_metadata.json from puppet-agent#master with the following update:
```
diff --git a/configs/projects/puppet-agent.rb b/configs/projects/puppet-agent.rb
index 221b7893..765580f9 100644
--- a/configs/projects/puppet-agent.rb
+++ b/configs/projects/puppet-agent.rb
@@ -12,7 +12,8 @@ project "puppet-agent" do |proj|

   settings_uri = File.join(runtime_details['location'], "#{proj.settings[:puppet_runtime_basename]}.settings.yaml")
   sha1sum_uri = "#{settings_uri}.sha1"
-  proj.inherit_yaml_settings(settings_uri, sha1sum_uri)
+  metadata_uri = File.join(runtime_details['location'], "#{runtime_details['version']}.build_metadata.agent-runtime-master.#{platform.name}.json")
+  proj.inherit_yaml_settings(settings_uri, sha1sum_uri, metadata_uri: metadata_uri)

   # (PA-678) pe-r10k versions prior to 2.5.0.0 ship gettext gems.
   # Since we also ship those gems as part of puppet-agent
```

built with this branch of vanagon. This tests the loading build_metadata from upstream project via url
```
{
  "packaging_type": {
    "vanagon": "0.15.32.6.g45595c0"
  },
  "version": "6.14.0.132.g9ecf64f9",
  "components": {
    "runtime-agent": {
    },
    "openssl-1.1.1": {
      "version": "1.1.1d",
      "url": "https://openssl.org/source/openssl-1.1.1d.tar.gz"
    },
    "curl": {
      "version": "7.68.0",
      "url": "https://curl.haxx.se/download/curl-7.68.0.tar.gz"
    },
    "puppet-ca-bundle": {
      "version": "1.0.8",
      "url": "git://github.com/puppetlabs/puppet-ca-bundle.git",
      "ref": "refs/tags/1.0.8"
    },
    "ruby-2.5.7": {
      "version": "2.5.7",
      "url": "https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.7.tar.gz"
    },
    "augeas": {
      "version": "1.12.0",
      "url": "http://download.augeas.net/augeas-1.12.0.tar.gz"
    },
    "libxml2": {
      "version": "2.9.8",
      "url": "http://xmlsoft.org/sources/libxml2-2.9.8.tar.gz"
    },
    "libxslt": {
      "version": "1.1.33",
      "url": "http://xmlsoft.org/sources/libxslt-1.1.33.tar.gz"
    },
    "ruby-augeas": {
      "version": "0.5.0",
      "url": "http://download.augeas.net/ruby/ruby-augeas-0.5.0.tgz"
    },
    "ruby-shadow": {
      "version": "2.5.0",
      "url": "git://github.com/apalmblad/ruby-shadow",
      "ref": "refs/tags/2.5.0"
    },
    "ruby-selinux": {
      "version": "2.0.94",
      "url": "https://raw.githubusercontent.com/wiki/SELinuxProject/selinux/files/releases/20100525/devel/libselinux-2.0.94.tar.gz"
    },
    "pl-ruby-patch": {
    },
    "rubygem-hocon": {
      "version": "1.3.0",
      "url": "https://rubygems.org/downloads/hocon-1.3.0.gem"
    },
    "rubygem-deep_merge": {
      "version": "1.0.1",
      "url": "https://rubygems.org/downloads/deep_merge-1.0.1.gem"
    },
    "rubygem-net-ssh": {
      "version": "4.2.0",
      "url": "https://rubygems.org/downloads/net-ssh-4.2.0.gem"
    },
    "rubygem-semantic_puppet": {
      "version": "1.0.2",
      "url": "https://rubygems.org/downloads/semantic_puppet-1.0.2.gem"
    },
    "rubygem-text": {
      "version": "1.3.1",
      "url": "https://rubygems.org/downloads/text-1.3.1.gem"
    },
    "rubygem-locale": {
      "version": "2.1.2",
      "url": "https://rubygems.org/downloads/locale-2.1.2.gem"
    },
    "rubygem-gettext": {
      "version": "3.2.2",
      "url": "https://rubygems.org/downloads/gettext-3.2.2.gem"
    },
    "rubygem-fast_gettext": {
      "version": "1.1.2",
      "url": "https://rubygems.org/downloads/fast_gettext-1.1.2.gem"
    },
    "rubygem-concurrent-ruby": {
      "version": "1.1.5",
      "url": "https://rubygems.org/downloads/concurrent-ruby-1.1.5.gem"
    },
    "rubygem-ffi": {
      "version": "1.9.25",
      "url": "https://rubygems.org/downloads/ffi-1.9.25.gem"
    },
    "rubygem-multi_json": {
      "version": "1.13.1",
      "url": "https://rubygems.org/downloads/multi_json-1.13.1.gem"
    },
    "rubygem-optimist": {
      "version": "3.0.0",
      "url": "https://rubygems.org/downloads/optimist-3.0.0.gem"
    },
    "rubygem-highline": {
      "version": "1.6.21",
      "url": "https://rubygems.org/downloads/highline-1.6.21.gem"
    },
    "rubygem-hiera-eyaml": {
      "version": "3.2.0",
      "url": "https://rubygems.org/downloads/hiera-eyaml-3.2.0.gem"
    },
    "rubygem-httpclient": {
      "version": "2.8.3",
      "url": "https://rubygems.org/downloads/httpclient-2.8.3.gem"
    },
    "rubygem-thor": {
      "version": "1.0.1",
      "url": "https://rubygems.org/downloads/thor-1.0.1.gem"
    },
    "rubygem-sys-filesystem": {
      "version": "1.3.2",
      "url": "https://rubygems.org/downloads/sys-filesystem-1.3.2.gem"
    },
    "boost": {
      "version": "1.69.0",
      "url": "http://downloads.sourceforge.net/project/boost/boost/1.69.0/boost_1_69_0.tar.gz"
    },
    "yaml-cpp": {
      "version": "yaml-cpp-0.6.2",
      "url": "git://github.com/jbeder/yaml-cpp.git",
      "ref": "refs/tags/yaml-cpp-0.6.2"
    },
    "puppet": {
      "version": "6.14.0-86-g30768e4683",
      "url": "git://github.com/puppetlabs/puppet.git",
      "ref": "30768e4683ada87bd852d95125313fce0f80762e"
    },
    "facter": {
      "version": "3.14.9-14-g81e44e71",
      "url": "git://github.com/puppetlabs/facter.git",
      "ref": "81e44e71dc1e6757bff5d554fa6b5bb7a8aa29c6"
    },
    "facter-ng": {
      "version": "4.0.13-11-g4747ca5",
      "url": "git://github.com/puppetlabs/facter-ng.git",
      "ref": "4747ca522b4e7c8ea678460538103582d7ca4e86"
    },
    "hiera": {
      "version": "3.6.0",
      "url": "git://github.com/puppetlabs/hiera.git",
      "ref": "refs/tags/3.6.0"
    },
    "leatherman": {
      "version": "1.11.0",
      "url": "git://github.com/puppetlabs/leatherman.git",
      "ref": "ae948ace4f80afd41e6dafc75c0236d895099263"
    },
    "cpp-hocon": {
      "version": "0.2.0",
      "url": "git://github.com/puppetlabs/cpp-hocon.git",
      "ref": "refs/tags/0.2.0"
    },
    "cpp-pcp-client": {
      "version": "1.6.1-6-g121102a",
      "url": "git://github.com/puppetlabs/cpp-pcp-client.git",
      "ref": "121102a8f52529b134c3b50be905395e7670ba7a"
    },
    "pxp-agent": {
      "version": "1.15.2-15-gb88e88b",
      "url": "git://github.com/puppetlabs/pxp-agent.git",
      "ref": "b88e88bee6c1ea0217fbf1ff39ae44438702ce58"
    },
    "libwhereami": {
      "version": "0.4.0",
      "url": "git://github.com/puppetlabs/libwhereami.git",
      "ref": "05c5d65373894dc37983d8e5f158f12f09fb9b02"
    },
    "puppet-runtime": {
      "version": "202003270",
      "url": "http://builds.delivery.puppetlabs.net/puppet-runtime/202003270/artifacts/agent-runtime-master-202003270.el-7-x86_64.tar.gz"
    },
    "puppet-resource_api": {
      "version": "1.8.13-3-g4a20175",
      "url": "git://github.com/puppetlabs/puppet-resource_api.git",
      "ref": "4a2017534a79c0f2298bb4e9244c81e58c8c78f5"
    },
    "virt-what": {
      "version": "1.18",
      "url": "https://people.redhat.com/~rjones/virt-what/files/virt-what-1.18.tar.gz"
    },
    "dmidecode": {
      "version": "2.12",
      "url": "http://download.savannah.gnu.org/releases/dmidecode/dmidecode-2.12.tar.gz"
    },
    "shellpath": {
      "version": "2015-09-18"
    },
    "runtime": {
    },
    "wrapper-script": {
    },
    "module-puppetlabs-augeas_core": {
      "version": "1.0.5",
      "url": "https://github.com/puppetlabs/puppetlabs-augeas_core.git",
      "ref": "refs/tags/1.0.5"
    },
    "module-puppetlabs-cron_core": {
      "version": "1.0.3",
      "url": "https://github.com/puppetlabs/puppetlabs-cron_core.git",
      "ref": "refs/tags/1.0.3"
    },
    "module-puppetlabs-host_core": {
      "version": "1.0.3",
      "url": "https://github.com/puppetlabs/puppetlabs-host_core.git",
      "ref": "refs/tags/1.0.3"
    },
    "module-puppetlabs-mount_core": {
      "version": "1.0.4",
      "url": "https://github.com/puppetlabs/puppetlabs-mount_core.git",
      "ref": "refs/tags/1.0.4"
    },
    "module-puppetlabs-scheduled_task": {
      "version": "1.0.0",
      "url": "https://github.com/puppetlabs/puppetlabs-scheduled_task.git",
      "ref": "refs/tags/1.0.0"
    },
    "module-puppetlabs-selinux_core": {
      "version": "1.0.4",
      "url": "https://github.com/puppetlabs/puppetlabs-selinux_core.git",
      "ref": "refs/tags/1.0.4"
    },
    "module-puppetlabs-sshkeys_core": {
      "version": "1.0.3",
      "url": "https://github.com/puppetlabs/puppetlabs-sshkeys_core.git",
      "ref": "refs/tags/1.0.3"
    },
    "module-puppetlabs-yumrepo_core": {
      "version": "1.0.6",
      "url": "https://github.com/puppetlabs/puppetlabs-yumrepo_core.git",
      "ref": "refs/tags/1.0.6"
    },
    "module-puppetlabs-zfs_core": {
      "version": "1.0.4",
      "url": "https://github.com/puppetlabs/puppetlabs-zfs_core.git",
      "ref": "refs/tags/1.0.4"
    },
    "module-puppetlabs-zone_core": {
      "version": "1.0.3",
      "url": "https://github.com/puppetlabs/puppetlabs-zone_core.git",
      "ref": "refs/tags/1.0.3"
    },
    "cleanup": {
    }
  },
  "build_time": "2020-04-02T11:46:47-07:00"
}
```

**Comment by underscorgan** [comment]
build_metadata.json from a pdk#master build with no changes. This tests loading metadata from an upstream git repo
```
{
  "packaging_type": {
    "vanagon": "0.15.32.6.g45595c0"
  },
  "version": "1.18.0.0.pre.14.g62575f9",
  "components": {
    "openssl-1.0.2": {
      "version": "1.0.2u",
      "url": "https://openssl.org/source/openssl-1.0.2u.tar.gz"
    },
    "curl": {
      "version": "7.68.0",
      "url": "https://curl.haxx.se/download/curl-7.68.0.tar.gz"
    },
    "git": {
      "version": "2.24.0",
      "url": "https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.24.0.tar.gz"
    },
    "runtime-pdk": {
    },
    "puppet-ca-bundle": {
      "url": "git://github.com/puppetlabs/puppet-ca-bundle.git",
      "ref": "refs/tags/1.0.8"
    },
    "augeas": {
      "version": "1.8.1",
      "url": "http://download.augeas.net/augeas-1.8.1.tar.gz"
    },
    "libxml2": {
      "version": "2.9.8",
      "url": "http://xmlsoft.org/sources/libxml2-2.9.8.tar.gz"
    },
    "libxslt": {
      "version": "1.1.33",
      "url": "http://xmlsoft.org/sources/libxslt-1.1.33.tar.gz"
    },
    "ruby-2.4.9": {
      "version": "2.4.9",
      "url": "https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.9.tar.gz"
    },
    "ruby-augeas": {
      "version": "0.5.0",
      "url": "http://download.augeas.net/ruby/ruby-augeas-0.5.0.tgz"
    },
    "ruby-selinux": {
      "version": "2.0.94",
      "url": "https://raw.githubusercontent.com/wiki/SELinuxProject/selinux/files/releases/20100525/devel/libselinux-2.0.94.tar.gz"
    },
    "ruby-stomp": {
      "version": "1.4.4",
      "url": "https://rubygems.org/downloads/stomp-1.4.4.gem"
    },
    "rubygem-ffi": {
      "version": "1.9.25",
      "url": "https://rubygems.org/downloads/ffi-1.9.25.gem"
    },
    "rubygem-locale": {
      "version": "2.1.2",
      "url": "https://rubygems.org/downloads/locale-2.1.2.gem"
    },
    "rubygem-text": {
      "version": "1.3.1",
      "url": "https://rubygems.org/downloads/text-1.3.1.gem"
    },
    "rubygem-gettext": {
      "version": "3.2.2",
      "url": "https://rubygems.org/downloads/gettext-3.2.2.gem"
    },
    "rubygem-fast_gettext": {
      "version": "1.1.2",
      "url": "https://rubygems.org/downloads/fast_gettext-1.1.2.gem"
    },
    "rubygem-gettext-setup": {
      "version": "0.31",
      "url": "https://rubygems.org/downloads/gettext-setup-0.31.gem"
    },
    "rubygem-minitar": {
      "version": "0.6.1",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/minitar-0.6.1.gem"
    },
    "ruby-2.1.9": {
      "version": "2.1.9",
      "url": "https://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.9.tar.gz"
    },
    "ruby-2.1-augeas": {
      "version": "0.5.0",
      "url": "http://download.augeas.net/ruby/ruby-augeas-0.5.0.tgz"
    },
    "ruby-2.1-selinux": {
      "version": "2.0.94",
      "url": "https://raw.githubusercontent.com/wiki/SELinuxProject/selinux/files/releases/20100525/devel/libselinux-2.0.94.tar.gz"
    },
    "ruby-2.1-stomp": {
      "version": "1.4.4",
      "url": "https://rubygems.org/downloads/stomp-1.4.4.gem"
    },
    "ruby-2.5.7": {
      "version": "2.5.7",
      "url": "https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.7.tar.gz"
    },
    "ruby-2.5-augeas": {
      "version": "0.5.0",
      "url": "http://download.augeas.net/ruby/ruby-augeas-0.5.0.tgz"
    },
    "ruby-2.5-selinux": {
      "version": "2.0.94",
      "url": "https://raw.githubusercontent.com/wiki/SELinuxProject/selinux/files/releases/20100525/devel/libselinux-2.0.94.tar.gz"
    },
    "ruby-2.5-stomp": {
      "version": "1.4.4",
      "url": "https://rubygems.org/downloads/stomp-1.4.4.gem"
    },
    "rubygem-bundler": {
      "version": "1.16.1",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/rubygems/gems/bundler-1.16.1.gem"
    },
    "pdk-runtime": {
      "version": "202003120",
      "url": "http://builds.puppetlabs.lan/puppet-runtime/202003120/artifacts/pdk-runtime-202003120.el-7-x86_64.tar.gz"
    },
    "rubygem-colored": {
      "version": "1.2",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/colored-1.2.gem"
    },
    "rubygem-cri": {
      "version": "2.10.1",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/cri-2.10.1.gem"
    },
    "rubygem-childprocess": {
      "version": "0.7.1",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/childprocess-0.7.1.gem"
    },
    "rubygem-necromancer": {
      "version": "0.5.0",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/necromancer-0.5.0.gem"
    },
    "rubygem-tty-color": {
      "version": "0.5.0",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/tty-color-0.5.0.gem"
    },
    "rubygem-equatable": {
      "version": "0.6.1",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/equatable-0.6.1.gem"
    },
    "rubygem-pastel": {
      "version": "0.7.3",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/pastel-0.7.3.gem"
    },
    "rubygem-wisper": {
      "version": "2.0.0",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/wisper-2.0.0.gem"
    },
    "rubygem-tty-cursor": {
      "version": "0.7.0",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/tty-cursor-0.7.0.gem"
    },
    "rubygem-hitimes": {
      "version": "1.3.0",
      "url": "https://rubygems.org/downloads/hitimes-1.3.0.gem"
    },
    "rubygem-tty-screen": {
      "version": "0.7.0",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/tty-screen-0.7.0.gem"
    },
    "rubygem-tty-reader": {
      "version": "0.6.0",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/tty-reader-0.6.0.gem"
    },
    "rubygem-tty-prompt": {
      "version": "0.19.0",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/tty-prompt-0.19.0.gem"
    },
    "rubygem-public_suffix": {
      "version": "3.0.0",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/public_suffix-3.0.0.gem"
    },
    "rubygem-addressable": {
      "version": "2.5.2",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/addressable-2.5.2.gem"
    },
    "rubygem-json-schema": {
      "version": "2.8.0",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/json-schema-2.8.0.gem"
    },
    "rubygem-concurrent-ruby": {
      "version": "1.1.5",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/concurrent-ruby-1.1.5.gem"
    },
    "rubygem-facter": {
      "version": "2.5.1",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/facter-2.5.1.gem"
    },
    "rubygem-httpclient": {
      "version": "2.8.3",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/httpclient-2.8.3.gem"
    },
    "rubygem-deep_merge": {
      "version": "1.2.1",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/deep_merge-1.2.1.gem"
    },
    "rubygem-tty-spinner": {
      "version": "0.9.1",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/tty-spinner-0.9.1.gem"
    },
    "rubygem-json_pure": {
      "version": "2.1.0",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/json_pure-2.1.0.gem"
    },
    "rubygem-tty-which": {
      "version": "0.4.1",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/tty-which-0.4.1.gem"
    },
    "rubygem-diff-lcs": {
      "version": "1.3",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/diff-lcs-1.3.gem"
    },
    "rubygem-pathspec": {
      "version": "0.2.1",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/pathspec-0.2.1.gem"
    },
    "rubygem-mini_portile2-for-ruby-2.1.0": {
      "version": "2.3.0",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/mini_portile2-2.3.0.gem"
    },
    "rubygem-nokogiri-for-ruby-2.1.0": {
      "version": "1.8.5",
      "url": "http://rubygems.org/downloads/nokogiri-1.8.5.gem"
    },
    "rubygem-mini_portile2": {
      "version": "2.4.0",
      "url": "https://artifactory.delivery.puppetlabs.net/artifactory/generic/buildsources/mini_portile2-2.4.0.gem"
    },
    "rubygem-nokogiri": {
      "version": "1.10.9",
      "url": "http://rubygems.org/downloads/nokogiri-1.10.9.gem"
    },
    "rubygem-pdk": {
      "version": "1.18.0.pre",
      "url": "https://github.com/puppetlabs/pdk",
      "ref": "9fd0f37d8b2cc02dbdc5de84981ad884b95ec67b"
    },
    "pdk-templates": {
      "version": "unknown",
      "url": "https://github.com/puppetlabs/pdk-templates",
      "ref": "0e871d085fbb8da16f66ebae3be9c00701a5bdb0"
    },
    "puppet-specifications": {
      "version": "4.6.0-250-g0f01004",
      "url": "git@github.com:puppetlabs/puppet-specifications.git",
      "ref": "master"
    },
    "puppet-forge-api": {
      "url": "git@github.com:puppetlabs/puppet-forge-api.git",
      "ref": "master"
    },
    "gem-prune": {
    },
    "pdk-create-ruby-tarballs": {
    },
    "shellpath": {
    }
  },
  "build_time": "2020-04-02T11:50:35-07:00"
}
```

**Comment by sarameisburger** [comment]
Woohoo this is awesome! I think it'd be worth it to add something in the readme about how to utilize this

**Comment by underscorgan** [comment]
@sarameisburger 😐 I looked into adding this into the README  but it is *very* sparse and doesn't really have anywhere that goes into details about the dsl methods at all. I updated the CHANGELOG to include usage details there instead.s

**Comment by sarameisburger** [comment]
lgtm!

**Pull request merged**
