### PR TITLE
(maint) Revert change to default output dir

### PR DESCRIPTION
**Pull request by underscorgan**
We should maintain defaults while still making it easy to overwrite the output dir.

### CODE REVIEW

**Comment by shrug** [comment]
👍

**Comment by shrug** [comment]
still 👍 

Maybe even 👍 er

**Comment by underscorgan** [comment]
Deb fix not quite working.

**Comment by underscorgan** [comment]
Test failures were due to pebcak

**Comment by shrug** [comment]
Still super 👍

**Pull request merged**
