### PR TITLE
(maint) Update CHANGELOG.md for 0.3.18 release

### PR DESCRIPTION
**Pull request by haus**

### CODE REVIEW

**Comment by geoffnichols** [comment]
:+1:

**Comment by MikaelSmith** [comment]
This looks up-to-date. :+1:

**Comment by kylog** [comment]
Will you do a gem release of 0.3.18 to rubygems?

**Comment by haus** [comment]
@kylog i was just talking about that. yea, i'll push it to the mirror and to rubygems.org. gemfiles can be updated to take advantage then and we should need less gemfile updates to opt into new versions.

**Comment by kylog** [comment]
That's what I was thinking. Would this mean we could actually use pessimistic versions?

**Comment by haus** [comment]
@kylog that's the idea yea

**Pull request merged**
