### PR TITLE
(maint) Allow Vanagon to override `cp`

### PR DESCRIPTION
**Pull request by melissa**
This PR also sets `@install` for windows and fixes a typo

### CODE REVIEW

**Comment by stahnma** [comment]
Why is this needed if the default is still /usr/bin/cp ?  (I'd prefer why to be in the commit messages)

**Comment by melissa** [comment]
It's cygwin cp versus windows cp. We want to ensure it's using cygwin cp. Just like with find and sort. I need to fix the tests though.

**Comment by melissa** [comment]
@stahnma okay, I fixed tests and updated the commit messages. We're defaulting to `cp` for all platforms except windows, where we need to use the cygwin `/usr/bin/cp`

**Comment by stahnma** [comment]
Im still confused, isn't cp normally /usr/bin/cp?

**Comment by ScottGarman** [comment]
:+1:

**Pull request merged**
