### PR TITLE
(VANAGON-109) Fix postinst to not break for empty trigger scripts

### PR DESCRIPTION
**Pull request by sarameisburger**
Bash doesn't like empty if statements

### CODE REVIEW

**Comment by sarameisburger** [comment]
[postinst.txt](https://github.com/puppetlabs/vanagon/files/1344939/postinst.txt)

**Comment by underscorgan** [comment]
@sarameisburger have you run a test build with these?

**Comment by sarameisburger** [comment]
Ran a build and nothing broke

**Pull request merged**
