### PR TITLE
(CPR-248) Add link to files list in link DSL method

### PR DESCRIPTION
**Pull request by haus**
Previously links were not added to the files list which meant that they
would not be collected if they fell outside of the directories being
watched by vanagon. This commit adds them to the files list.
The cp calls in the spec and rules files need the -R flag added to
ensure that links are not dereferenced and are copied as is, which would
otherwise break packaging.

### CODE REVIEW

**Comment by stahnma** [comment]
:+1:

**Comment by haus** [comment]
I need to look at AIX here a bit. -R might not be the right flag there.

**Comment by haus** [comment]
Nope, this works on aix as well. all clear.

**Comment by melissa** [comment]
Will this preserve the links, or just clobber them and turn them into normal files? How does tar handle this?

**Comment by haus** [comment]
-R copies the link without dereferencing. tar archives the link.

**Pull request merged**
