### PR TITLE
(RE-6464) Force inclusion of Custom Actions

### PR DESCRIPTION
**Pull request by jcoconnor**
Using Group References as per:
http://stackoverflow.com/questions/7978066/how-to-include-fragments-in-wix

This requires Puppet-Agent PR https://github.com/puppetlabs/puppet-agent/pull/559 to be merged.

### CODE REVIEW

**Comment by McdonaldSeanp** [comment]
I would like to set some sort of naming convention here and have all the component groups names similarly. My suggestion is to have all the ids be camel case and be correctly plural/singular i.e.: 

ProductComponents
RegistryComponents
ServiceList
CustomActionProperties
CustomActionSequences
CustomActions

**Comment by jcoconnor** [comment]
Good idea - would modify the list somewhat though:
ProductComponents
RegistryComponents
ServiceList
Properties
Sequences
CustomActions

**Comment by jpogran** [comment]
I concur with Sean on naming convention and spelling. It more closely follows WiX conventions and reads better to me.

**Comment by jcoconnor** [comment]
After discussion at the workshop today, we decided on (@jpogran & @McdonaldSeanp correct me if I have missed anything)
1. Prefix all Pseudo-Includes with "Fragment" to indicate we are forcing a fragment to be included.
2. Eliminate use of "_" in IDs.
3. Change "Components" to "Component" in components/dsl.rb for service IDs.
4. Some format/indentation consistency tidy ups to the Wix elements where multiple attributes are used.

Updated PR's will be submitted shortly.

**Comment by jcoconnor** [comment]
@McdonaldSeanp @jpogran @melissa PR Review changes applied - ready for review again.

**Comment by McdonaldSeanp** [comment]
:+1:

**Pull request merged**
