### PR TITLE
(VANAGON-168) Remove Fedora 30 x86_64 from vanagon

### PR DESCRIPTION
**Pull request by BobosilaVictor**
Please add all notable changes to the "Unreleased" section of the CHANGELOG.

### CODE REVIEW

**Comment by ciprianbadescu** [comment]
/cc: @puppetlabs/bolt , @puppetlabs/pdk , @puppetlabs/night-s-watch

**Comment by lucywyman** [comment]
These are [still documented as supported for Puppet and the Puppet agent](https://puppet.com/docs/puppet/7/system_requirements.html). Does this require a major version bump for us to remove these platforms altogether?

**Comment by ciprianbadescu** [comment]
@lucywyman , the platforms will be removed for the next puppet-agent release. Changes were already merged.
I don't think we have to remove them in sync, but we need to make sure all projects are no longer using a platform before removing it from vanagon and other common projects.

**Review by lucywyman — APPROVED** [review]

**Comment by joshcooper** [comment]
@BobosilaVictor could you resolve changelog conflicts?

**Review by GabrielNagy — APPROVED** [review]

**Pull request merged**
