### PR TITLE
(VANAGON-10) Add build command to build tarballs of each component

### PR DESCRIPTION
**Pull request by McdonaldSeanp**
This is the first step in caching components

Please read the commit messages for information on the design

This PR contains work from https://github.com/puppetlabs/vanagon/pull/409 , so this PR is blocked on that.

NOTE**\* ~~this PR does not attempt to solve any kind of versioning for the component artifacts, this will be solved later in the process of component caching~~
We should use the component's version

### CODE REVIEW

**Comment by stahnma** [comment]
Is there a design doc on the caching components plan? I'd like to see how this fits in exactly.

**Comment by McdonaldSeanp** [comment]
@stahnma there's an epic: https://tickets.puppetlabs.com/browse/VANAGON-9

I tried to describe as much as I could in the tickets.

**Comment by underscorgan** [comment]
@McdonaldSeanp we definitely want to review this but realistically it's not going to happen this week.  We're going to take a look next week.

**Comment by McdonaldSeanp** [comment]
kk @underscorgan, btw there is also a design doc linked in the epic =)

**Comment by McdonaldSeanp** [comment]
btw, @underscorgan @mckern #409 still blocks this PR

**Comment by mckern** [comment]
Closing this as we're reconsidering what it'll take to improve build times.

**Pull request closed without merging**
