### PR TITLE
Use id, private_ip address attrribute instead of symbol

### PR DESCRIPTION
**Pull request by cwood**
Iv realized after this was merged than when I try to access :symboles like id or private_ip_address that it doesnt work and fails out. So I just call the function directly then access them through there dot accesory.

### CODE REVIEW

**Comment by cwood** [comment]
@mckern Any chances I can get this merged?

**Comment by mckern** [comment]
@cwood any chance I can get a spec test around this behavior? Worst case scenario, I'm willing to merge first and help you write a spec test in another PR.

**Comment by cwood** [comment]
I guess thats the big question about how to dry run with making these ec2 calls.

**Comment by mckern** [comment]
Let's talk about [stubbed responses and mocks](http://docs.aws.amazon.com/sdkforruby/api/Aws/ClientStubs.html)

**Comment by cwood** [comment]
Ah okay I can probalby use that to start testing that out and initialze with some fake stuff

**Comment by mckern** [comment]
Hey @cwood I've had a change of heart about the validity of asking for tests on code that didn't have tests already. I've reviewed this, and I think it'll do the right thing. I'm 👍 on it. Stand by for merge!

**Comment by cwood** [comment]
Thanks @mckern I did run this locally on my own builds.

**Pull request merged**
