### PR TITLE
(maint) Remove project subdirectory

### PR DESCRIPTION
**Pull request by melissa**
It's unnecessary and adds to the number of characters I have to type

### CODE REVIEW

**Comment by McdonaldSeanp** [comment]
I'm assuming at some point it rips out the whole dir yes?

**Comment by melissa** [comment]
@McdonaldSeanp I'm not sure I follow your comment....

**Comment by McdonaldSeanp** [comment]
@melissa nothing, I just totally forgot that all this is happening on a pooler image so my comment doesn't matter. Ignore me =)

**Comment by McdonaldSeanp** [comment]
i'm :+1:

**Comment by jcoconnor** [comment]
:+1: 
Makes sense - LGTM

**Pull request merged**
